name: "Java Maven CI"

# Trigger workflow on pushes and pull requests to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    
    - name: Set up JDK 
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' 
        java-version: '17'   
    #build the project with maven
    - name: Build with Maven
      run: 
        mvn clean install
# run the tests with maven 
    - name: Unit Tests
      run: mvn test
        
