name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to 'main'
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests targeting 'main'

jobs:
  # CI Job (Continuous Integration)
  ci:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js (if using Node.js, or adjust for your project)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust to your project’s Node.js version

      # Install dependencies (change to match your environment)
      - name: Install dependencies
        run: npm install  # For Node.js projects, change if necessary

      # Run tests (using npm, change if necessary)
      - name: Run tests
        run: npm test  # Adjust to match your testing framework

      # Build your project (adjust as per your build process)
      - name: Build the project
        run: npm run build  # Replace with your actual build command

  # CD Job (Continuous Deployment)
  deploy:
    runs-on: ubuntu-latest
    needs: ci  # The deploy job depends on the success of the CI job
    if: github.ref == 'refs/heads/main'  # Only deploy on push to main

    steps:
      # Checkout code again for deployment
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH (ensure you store your SSH private key in GitHub secrets)
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add this key to GitHub secrets

      # Deploy to remote server via SSH (e.g., copy files or restart the server)
      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server-ip << 'EOF'
          cd /path/to/your/project
          git pull origin main  # Pull the latest changes
          npm install  # Install any new dependencies
          pm2 restart your-app  # Restart the app (replace with your process manager)
          EOF
